#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("XamHawkPush.Resource", IsApplication=true)]

namespace XamHawkPush
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int buttonSize = 2130771968;
			
			// aapt resource value: 0x7f010005
			public const int circleCrop = 2130771973;
			
			// aapt resource value: 0x7f010001
			public const int colorScheme = 2130771969;
			
			// aapt resource value: 0x7f010004
			public const int imageAspectRatio = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int imageAspectRatioAdjust = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int scopeUris = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050008
			public const int common_action_bar_splitter = 2131034120;
			
			// aapt resource value: 0x7f050011
			public const int common_google_signin_btn_text_dark = 2131034129;
			
			// aapt resource value: 0x7f050009
			public const int common_google_signin_btn_text_dark_default = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int common_google_signin_btn_text_dark_disabled = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int common_google_signin_btn_text_dark_focused = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int common_google_signin_btn_text_dark_pressed = 2131034122;
			
			// aapt resource value: 0x7f050012
			public const int common_google_signin_btn_text_light = 2131034130;
			
			// aapt resource value: 0x7f05000d
			public const int common_google_signin_btn_text_light_default = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int common_google_signin_btn_text_light_disabled = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int common_google_signin_btn_text_light_focused = 2131034128;
			
			// aapt resource value: 0x7f05000e
			public const int common_google_signin_btn_text_light_pressed = 2131034126;
			
			// aapt resource value: 0x7f050013
			public const int common_plus_signin_btn_text_dark = 2131034131;
			
			// aapt resource value: 0x7f050000
			public const int common_plus_signin_btn_text_dark_default = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int common_plus_signin_btn_text_dark_disabled = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int common_plus_signin_btn_text_dark_focused = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int common_plus_signin_btn_text_dark_pressed = 2131034113;
			
			// aapt resource value: 0x7f050014
			public const int common_plus_signin_btn_text_light = 2131034132;
			
			// aapt resource value: 0x7f050004
			public const int common_plus_signin_btn_text_light_default = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int common_plus_signin_btn_text_light_disabled = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int common_plus_signin_btn_text_light_focused = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int common_plus_signin_btn_text_light_pressed = 2131034117;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f080000
			public const int activity_horizontal_margin = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int activity_vertical_margin = 2131230721;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int common_full_open_on_phone = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_google_signin_btn_icon_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_google_signin_btn_icon_dark_disabled = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_google_signin_btn_icon_dark_focused = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_google_signin_btn_icon_dark_normal = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_google_signin_btn_icon_dark_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_google_signin_btn_icon_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_light_disabled = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_light_focused = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_light_normal = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_icon_light_pressed = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_text_dark = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_text_dark_disabled = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_text_dark_focused = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_text_dark_normal = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_text_dark_pressed = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_light = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_light_disabled = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_light_focused = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_text_light_normal = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_text_light_pressed = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_ic_googleplayservices = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_plus_signin_btn_icon_dark = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_plus_signin_btn_icon_dark_disabled = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_plus_signin_btn_icon_dark_focused = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_plus_signin_btn_icon_dark_normal = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_plus_signin_btn_icon_dark_pressed = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_plus_signin_btn_icon_light = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int common_plus_signin_btn_icon_light_disabled = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int common_plus_signin_btn_icon_light_focused = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int common_plus_signin_btn_icon_light_normal = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int common_plus_signin_btn_icon_light_pressed = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int common_plus_signin_btn_text_dark = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int common_plus_signin_btn_text_dark_disabled = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int common_plus_signin_btn_text_dark_focused = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int common_plus_signin_btn_text_dark_normal = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int common_plus_signin_btn_text_dark_pressed = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int common_plus_signin_btn_text_light = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int common_plus_signin_btn_text_light_disabled = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int common_plus_signin_btn_text_light_focused = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int common_plus_signin_btn_text_light_normal = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int common_plus_signin_btn_text_light_pressed = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int shaccept = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int shaccount = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int shairport_shuttle = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int shalarm = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int shapppage = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int shaudio = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int shbad_mood = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int shbalance = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int shbar = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int shbeach_access = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int shbike = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int shbluetooth = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int shboat = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int shbookmark = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int shbreakfast = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int shbus = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int shcafe = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int shcake = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int shcall = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int shcamera = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int shcancel = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int shcar = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int shcasino = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int shcast = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int shcharts = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int shchat = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int shchild_care = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int shchild_friendly = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int shcloud = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int shcloud_download = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int shcloud_upload = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int shcreditcard = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int shdelete = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int shdinning = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int shdislike = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int shdissatisfied = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int shdo_not_disturb = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int shenablepush = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int sheuro = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int shfastforward = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int shfeedback = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int shfile_download = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int shfile_upload = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int shflag = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int shflight = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int shgiftcard = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int shgrocery_store = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int shgroup = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int shhand = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int shheart = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int shhome = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int shhospital = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int shhotel = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int shhourglass = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int shitness_center = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int shkey = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int shlater = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int shlibrary = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int shlightbulb = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int shlike = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int shlocation = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int shloyalty = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int shmembership = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int shmic = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int shmoney = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int shmood = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public const int shmovies = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public const int shneutral = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public const int shoffer = 2130837614;
			
			// aapt resource value: 0x7f02006f
			public const int shpause = 2130837615;
			
			// aapt resource value: 0x7f020070
			public const int shpayment = 2130837616;
			
			// aapt resource value: 0x7f020071
			public const int shperson = 2130837617;
			
			// aapt resource value: 0x7f020072
			public const int shpets = 2130837618;
			
			// aapt resource value: 0x7f020073
			public const int shpizza = 2130837619;
			
			// aapt resource value: 0x7f020074
			public const int shplay = 2130837620;
			
			// aapt resource value: 0x7f020075
			public const int shplay_circle = 2130837621;
			
			// aapt resource value: 0x7f020076
			public const int shpool = 2130837622;
			
			// aapt resource value: 0x7f020077
			public const int shquestionmark = 2130837623;
			
			// aapt resource value: 0x7f020078
			public const int shradio = 2130837624;
			
			// aapt resource value: 0x7f020079
			public const int shrailway = 2130837625;
			
			// aapt resource value: 0x7f02007a
			public const int shrate = 2130837626;
			
			// aapt resource value: 0x7f02007b
			public const int shrecord = 2130837627;
			
			// aapt resource value: 0x7f02007c
			public const int shredeem = 2130837628;
			
			// aapt resource value: 0x7f02007d
			public const int shreply = 2130837629;
			
			// aapt resource value: 0x7f02007e
			public const int shrestaurant = 2130837630;
			
			// aapt resource value: 0x7f02007f
			public const int shrestaurant_menu = 2130837631;
			
			// aapt resource value: 0x7f020080
			public const int shrun = 2130837632;
			
			// aapt resource value: 0x7f020081
			public const int shsatisfied = 2130837633;
			
			// aapt resource value: 0x7f020082
			public const int shschool = 2130837634;
			
			// aapt resource value: 0x7f020083
			public const int shsettings = 2130837635;
			
			// aapt resource value: 0x7f020084
			public const int shshare = 2130837636;
			
			// aapt resource value: 0x7f020085
			public const int shshipping = 2130837637;
			
			// aapt resource value: 0x7f020086
			public const int shshoppingcart = 2130837638;
			
			// aapt resource value: 0x7f020087
			public const int shsimplepush = 2130837639;
			
			// aapt resource value: 0x7f020088
			public const int shsms = 2130837640;
			
			// aapt resource value: 0x7f020089
			public const int shsnooz = 2130837641;
			
			// aapt resource value: 0x7f02008a
			public const int shstar = 2130837642;
			
			// aapt resource value: 0x7f02008b
			public const int shsubway = 2130837643;
			
			// aapt resource value: 0x7f02008c
			public const int shsupport = 2130837644;
			
			// aapt resource value: 0x7f02008d
			public const int shsync = 2130837645;
			
			// aapt resource value: 0x7f02008e
			public const int shtaxi = 2130837646;
			
			// aapt resource value: 0x7f02008f
			public const int shtoy = 2130837647;
			
			// aapt resource value: 0x7f020090
			public const int shtram = 2130837648;
			
			// aapt resource value: 0x7f020091
			public const int shtravelcard = 2130837649;
			
			// aapt resource value: 0x7f020092
			public const int shtrendingdown = 2130837650;
			
			// aapt resource value: 0x7f020093
			public const int shtv = 2130837651;
			
			// aapt resource value: 0x7f020094
			public const int shupdate = 2130837652;
			
			// aapt resource value: 0x7f020095
			public const int shvery_satisfied = 2130837653;
			
			// aapt resource value: 0x7f020096
			public const int shvolume = 2130837654;
			
			// aapt resource value: 0x7f020097
			public const int shwalk = 2130837655;
			
			// aapt resource value: 0x7f020098
			public const int shwallet = 2130837656;
			
			// aapt resource value: 0x7f020099
			public const int shwarning = 2130837657;
			
			// aapt resource value: 0x7f02009a
			public const int shwatch = 2130837658;
			
			// aapt resource value: 0x7f02009b
			public const int shwebsite = 2130837659;
			
			// aapt resource value: 0x7f02009c
			public const int shweekend = 2130837660;
			
			// aapt resource value: 0x7f02009d
			public const int shwhatshot = 2130837661;
			
			// aapt resource value: 0x7f02009e
			public const int shwork = 2130837662;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090006
			public const int adjust_height = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int adjust_width = 2131296263;
			
			// aapt resource value: 0x7f090003
			public const int auto = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int dark = 2131296260;
			
			// aapt resource value: 0x7f090000
			public const int icon_only = 2131296256;
			
			// aapt resource value: 0x7f090005
			public const int light = 2131296261;
			
			// aapt resource value: 0x7f090009
			public const int myButton = 2131296265;
			
			// aapt resource value: 0x7f090008
			public const int none = 2131296264;
			
			// aapt resource value: 0x7f090001
			public const int standard = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int wide = 2131296258;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int google_play_services_version = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int activity_shfeedback = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Main = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060020
			public const int BLUETOOTH_ENABLE_TOAST = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int STREETHAWK_BLUETOOTH_NEGATIVE = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int STREETHAWK_BLUETOOTH_POSITIVE = 2131099682;
			
			// aapt resource value: 0x7f060023
			public const int STREETHAWK_CALL_NEGATIVE = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int STREETHAWK_CALL_POSITIVE = 2131099684;
			
			// aapt resource value: 0x7f060025
			public const int STREETHAWK_FEEDBACK_CANCEL = 2131099685;
			
			// aapt resource value: 0x7f060026
			public const int STREETHAWK_FEEDBACK_HINT_CONTENT = 2131099686;
			
			// aapt resource value: 0x7f060027
			public const int STREETHAWK_FEEDBACK_HINT_TITLE = 2131099687;
			
			// aapt resource value: 0x7f060028
			public const int STREETHAWK_FEEDBACK_NEGATIVE = 2131099688;
			
			// aapt resource value: 0x7f060029
			public const int STREETHAWK_FEEDBACK_POSITIVE = 2131099689;
			
			// aapt resource value: 0x7f06002a
			public const int STREETHAWK_FEEDBACK_SUBMIT = 2131099690;
			
			// aapt resource value: 0x7f06002b
			public const int STREETHAWK_FEEDBACK_TOAST_ERROR = 2131099691;
			
			// aapt resource value: 0x7f06002c
			public const int STREETHAWK_FEEDBACK_TOAST_SUCCESS = 2131099692;
			
			// aapt resource value: 0x7f06002d
			public const int STREETHAWK_GROWTH_DEFAULT_EMAIL_BODY = 2131099693;
			
			// aapt resource value: 0x7f06002e
			public const int STREETHAWK_GROWTH_DEFAULT_EMAIL_SUBJECT = 2131099694;
			
			// aapt resource value: 0x7f06002f
			public const int STREETHAWK_LOCATION_NEGATIVE = 2131099695;
			
			// aapt resource value: 0x7f060030
			public const int STREETHAWK_LOCATION_POSITIVE = 2131099696;
			
			// aapt resource value: 0x7f060031
			public const int STREETHAWK_OPEN_APP_NEGATIVE = 2131099697;
			
			// aapt resource value: 0x7f060032
			public const int STREETHAWK_OPEN_APP_POSITIVE = 2131099698;
			
			// aapt resource value: 0x7f060033
			public const int STREETHAWK_PUSH_NEGATIVE = 2131099699;
			
			// aapt resource value: 0x7f060034
			public const int STREETHAWK_PUSH_POSITIVE = 2131099700;
			
			// aapt resource value: 0x7f060035
			public const int STREETHAWK_RATE_NEGATIVE = 2131099701;
			
			// aapt resource value: 0x7f060036
			public const int STREETHAWK_RATE_NEUTRAL = 2131099702;
			
			// aapt resource value: 0x7f060037
			public const int STREETHAWK_RATE_POSITIVE = 2131099703;
			
			// aapt resource value: 0x7f060038
			public const int STREETHAWK_RAW_JSON_NEGATIVE = 2131099704;
			
			// aapt resource value: 0x7f060039
			public const int STREETHAWK_RAW_JSON_POSITIVE = 2131099705;
			
			// aapt resource value: 0x7f06003a
			public const int STREETHAWK_SHOW_URL_CLOSE = 2131099706;
			
			// aapt resource value: 0x7f06003b
			public const int STREETHAWK_SHOW_URL_NEGATIVE = 2131099707;
			
			// aapt resource value: 0x7f06003c
			public const int STREETHAWK_SHOW_URL_POSITIVE = 2131099708;
			
			// aapt resource value: 0x7f060041
			public const int STREETHAWK_SIMPLE_CANCEL = 2131099713;
			
			// aapt resource value: 0x7f06003d
			public const int STREETHAWK_SIMPLE_MESSAGE_NOTIFICATION_POSITIVE = 2131099709;
			
			// aapt resource value: 0x7f06003e
			public const int STREETHAWK_SIMPLE_MESSAGE_POSITIVE = 2131099710;
			
			// aapt resource value: 0x7f060042
			public const int STREETHAWK_SIMPLE_OK = 2131099714;
			
			// aapt resource value: 0x7f06003f
			public const int STREETHAWK_UPDATE_NEGATIVE = 2131099711;
			
			// aapt resource value: 0x7f060040
			public const int STREETHAWK_UPDATE_POSITIVE = 2131099712;
			
			// aapt resource value: 0x7f060043
			public const int action_settings = 2131099715;
			
			// aapt resource value: 0x7f06001f
			public const int app_name = 2131099679;
			
			// aapt resource value: 0x7f06001d
			public const int auth_google_play_services_client_facebook_display_name = 2131099677;
			
			// aapt resource value: 0x7f06001c
			public const int auth_google_play_services_client_google_display_name = 2131099676;
			
			// aapt resource value: 0x7f060015
			public const int common_google_play_services_api_unavailable_text = 2131099669;
			
			// aapt resource value: 0x7f060007
			public const int common_google_play_services_enable_button = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int common_google_play_services_enable_text = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int common_google_play_services_enable_title = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int common_google_play_services_install_button = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int common_google_play_services_install_text_phone = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int common_google_play_services_install_text_tablet = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int common_google_play_services_install_title = 2131099649;
			
			// aapt resource value: 0x7f060010
			public const int common_google_play_services_invalid_account_text = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int common_google_play_services_invalid_account_title = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int common_google_play_services_network_error_text = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int common_google_play_services_network_error_title = 2131099661;
			
			// aapt resource value: 0x7f060000
			public const int common_google_play_services_notification_ticker = 2131099648;
			
			// aapt resource value: 0x7f060019
			public const int common_google_play_services_restricted_profile_text = 2131099673;
			
			// aapt resource value: 0x7f060018
			public const int common_google_play_services_restricted_profile_title = 2131099672;
			
			// aapt resource value: 0x7f060017
			public const int common_google_play_services_sign_in_failed_text = 2131099671;
			
			// aapt resource value: 0x7f060016
			public const int common_google_play_services_sign_in_failed_title = 2131099670;
			
			// aapt resource value: 0x7f06001e
			public const int common_google_play_services_unknown_issue = 2131099678;
			
			// aapt resource value: 0x7f060012
			public const int common_google_play_services_unsupported_text = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int common_google_play_services_unsupported_title = 2131099665;
			
			// aapt resource value: 0x7f060013
			public const int common_google_play_services_update_button = 2131099667;
			
			// aapt resource value: 0x7f060009
			public const int common_google_play_services_update_text = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int common_google_play_services_update_title = 2131099656;
			
			// aapt resource value: 0x7f06000c
			public const int common_google_play_services_updating_text = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int common_google_play_services_updating_title = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int common_google_play_services_wear_update_text = 2131099658;
			
			// aapt resource value: 0x7f060014
			public const int common_open_on_phone = 2131099668;
			
			// aapt resource value: 0x7f06001a
			public const int common_signin_button_text = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int common_signin_button_text_long = 2131099675;
			
			// aapt resource value: 0x7f060046
			public const int hello = 2131099718;
			
			// aapt resource value: 0x7f060044
			public const int hello_world = 2131099716;
			
			// aapt resource value: 0x7f060045
			public const int title_activity_shfeedback = 2131099717;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[]
			{
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] SignInButton = new int[]
			{
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
